### ISSUE TITLE
Not working :/

### ISSUE THREAD

**Issue by Seauxz** [QbDesu/Dynmap-Meets-Towny#1]
this hasent been working and there are a bunch of errors. I asked my server host support team ad they told me to reach the author. the plugin does not work :/

**Comment by QbDesu** [comment]
I haven't really worked on the plugin in a while.. If you tell me which type of server you are using Paper/Bukkit/Spigot and the versions of both the server and the plugins (Towny + optionally TownyChat) and provide me with the error logs I can look into it. The logs usually contain the aforementioned details as well.

**Comment by MarcoGYTV2** [comment]
hi there can u add a link to the actual towny downloaD OR PROVIDE US WITH A  download?
oops caps im too lazy to remove it ol
