### ISSUE TITLE
Towny

### ISSUE THREAD

**Issue by MarcoGYTV2** [QbDesu/Dynmap-Meets-Towny#2]
I cant find the towny plugin

**Comment by QbDesu** [comment]
https://lmddgtfy.net/?q=Towny%20Plugin

Keep in mind that if you want to use Dynmap-Meets-Towny as well that it hasn't been updated in more than 5 months so it might not be compatible. Also, this plugin will likely not be updated before Minecraft 1.17 and I will not update the 1.16 version in case there are breaking changes. Now that I think about it the server I plan to play on then won't even use Towny in the 1.17 update, so I guess this plugin won't even be updated and I probably won't put any effort into maintaining it. This plugin will also not be updated in case [Towny](https://townyadvanced.github.io) made some big changes to it's API which renders this plugin incompatible.
