### ISSUE TITLE
vars

### ISSUE THREAD

**Issue by Kostya-An** [QbDesu/Dynmap-Meets-Towny#3]
Hello! 
I would like to know what vars are there for the site?
That is, what can be specified in {{var}}

**Comment by QbDesu** [comment]
```sh
town_name
town_block_type
nation #used to check if it is in a nation
nation_prefix
nation_name
nation_postfix
mayor #used to check if there is a mayor
mayor_prefix
mayor_name
mayor_postfix
resident_count
resident_names #list of names
assistant_names #list of names
founded
pvp
mobs
public
explosion
fire
board
war
capital
economy #used to check if economy is enabled
balance
taxes
upkeep #used to check if upkeep is enabled
upkeep_cost
```

Keep in mind I haven't updated the plugin in months and don't plan on maintaining it in the future.
Look at https://github.com/QbDesu/Dynmap-Meets-Towny/blob/master/src/main/resources/templates/town_popup.html for usage examples.

**Comment by Kostya-An** [comment]
Thank you!
