### ISSUE TITLE
Different colours

### ISSUE THREAD

**Issue by Kostya-An** [QbDesu/Dynmap-Meets-Towny#4]
[question]
How to make cities in different colors, but at the same time cities consisting of one nation were the same color?
For example, there are five cities: A, B, C, D, E
A and B in the same nation
C and D to another
E without a nation
How to make
A and B were, for example, red
C and D blue
A E in yellow
And for other cities, different colors were generated

**Comment by Kostya-An** [comment]
Or gradient?

**Comment by Kostya-An** [comment]
Help me!

**Comment by QbDesu** [comment]
use the nationstyle config option. This project is unmaintained for over a year now, go away.
